config/routes.rb
Rails.application.routes.draw do
  resources :dailies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :set_daily, only: [:show, :edit, :update, :destroy]

  # GET /dailies
  # GET /dailies.json
  def index
    @dailies = Daily.all
  end

  # GET /dailies/1
  # GET /dailies/1.json
  def show
  end

  # GET /dailies/new
  def new
    @daily = Daily.new
  end

  # GET /dailies/1/edit
  def edit
  end

  # POST /dailies
  # POST /dailies.json
  def create
    @daily = Daily.new(daily_params)

    respond_to do |format|
      if @daily.save
        format.html { redirect_to @daily, notice: 'Daily was successfully created.' }
        format.json { render :show, status: :created, location: @daily }
      else
        format.html { render :new }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dailies/1
  # PATCH/PUT /dailies/1.json
  def update
    respond_to do |format|
      if @daily.update(daily_params)
        format.html { redirect_to @daily, notice: 'Daily was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily }
      else
        format.html { render :edit }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailies/1
  # DELETE /dailies/1.json
  def destroy
    @daily.destroy
    respond_to do |format|
      format.html { redirect_to dailies_url, notice: 'Daily was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @daily = Daily.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_params
      params.require(:daily).permit(:name, :date, :weight, :waist_size, :bfp, :bmi)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/views/dailies/_form.html.erb
<%= form_with(model: daily, local: true) do |form| %>
  <% if daily.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily.errors.count, "error") %> prohibited this daily from being saved:</h2>

      <ul>
        <% daily.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :waist_size %>
    <%= form.number_field :waist_size %>
  </div>

  <div class="field">
    <%= form.label :bfp %>
    <%= form.number_field :bfp %>
  </div>

  <div class="field">
    <%= form.label :bmi %>
    <%= form.number_field :bmi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dailies/edit.html.erb
<h1>Editing Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Show', @daily %> |
<%= link_to 'Back', dailies_path %>

app/views/dailies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dailies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Weight</th>
      <th>Waist Size</th>
      <th>BFP</th>
      <th>BMI</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dailies.each do |daily| %>
      <tr>
        <td><%= daily.name %></td>
        <td><%= daily.date %></td>
        <td><%= daily.weight %></td>
        <td><%= daily.waist_size %></td>
        <td><%= daily.bfp %></td>
        <td><%= daily.bmi %></td>
        <td><%= link_to 'Show', daily %></td>
        <td><%= link_to 'Edit', edit_daily_path(daily) %></td>
        <td><%= link_to 'Destroy', daily, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily', new_daily_path %>

app/views/dailies/new.html.erb
<h1>New Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Back', dailies_path %>

app/views/dailies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @daily.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @daily.date %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @daily.weight %>
</p>

<p>
  <strong>Waist size:</strong>
  <%= @daily.waist_size %>
</p>

<p>
  <strong>Bfp:</strong>
  <%= @daily.bfp %>
</p>

<p>
  <strong>Bmi:</strong>
  <%= @daily.bmi %>
</p>

<%= link_to 'Edit', edit_daily_path(@daily) %> |
<%= link_to 'Back', dailies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiggestLoser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>